### ISSUE TITLE
License Error during Matlab Run Action

### ISSUE THREAD

**Issue by bendhouseart** [matlab-actions/overview#4]
Currently getting the following error message from github actions after successful setup of Matlab:

``` /home/runner/work/_actions/matlab-actions/run-command/v1/dist/bin/run_matlab_command.sh cd('/tmp/run_matlab_command-kqqpJD'); command_79d7ece3_b0d2_4a8a_b21b_a94112f7d15b
  ======BEGIN LICENSE MANAGER ERROR======
  License checkout failed.
  License Manager Error 4402
  SSL Exception: error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure
  
  Troubleshoot this issue by visiting: 
  https://www.mathworks.com/support/lme/R2021a/4402
  
  Diagnostic Information:
  Feature: MATLAB_Distrib_Comp_Engine 
  License path:  
  Licensing error: 4402,0.======END LICENSE MANAGER ERROR======
  
Error: Error: The process '/home/runner/work/_actions/matlab-actions/run-command/v1/dist/bin/run_matlab_command.sh' failed with exit code 1
```

Just noticed this error in the last 1-2 days. Workflow had previously been working fine up until a confirmed 09/17/21 [here](https://github.com/openneuropet/BIDS-converter)

I am *not* a Matlab developer, I just play one on CI.  Any help or assistance would be greatly appreciated.

**Comment by mcafaro** [comment]
Thanks for getting in touch. This is due to an Online Licensing partial outage that is currently under investigation. Our apologies for the inconvenience, but we will resolve it as soon as possible. You should not have to do anything. Please check our status page for up to date details.
 
https://status.mathworks.com/

**Comment by bendhouseart** [comment]
@mcafaro oh that's excellent to hear (for me at least). Good luck to your dev ops folks!

**Comment by acampbel** [comment]
> @mcafaro oh that's excellent to hear (for me at least). Good luck to your dev ops folks!

@bendhouseart The Online Licensing service should be available and running now. Thank you for your patience.

**Comment by msafwanalam** [comment]
Hello! I am currently facing some issues in the setup matlab component. I have added the following in my yml file:
``` 
name: Run MATLAB Build on GitHub-Hosted Runner
on: [push]
jobs:
  my-job:
    name: Run MATLAB Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          products: Simulink Simulink_Test
      - name: Run build
        uses: matlab-actions/run-build@v2
        with:
          tasks: test
```
Just the basic setup, but it results in this:
![image](https://github.com/matlab-actions/.github/assets/30600469/1afb2008-a125-4fc5-ae7d-9e89ffccfc04)
Is there any additional setup required?
