### ISSUE TITLE
Should state be saved between steps?

### ISSUE THREAD

**Issue by H0R5E** [matlab-actions/overview#6]
Hi, I was just wondering if the behaviour I am seeing when calling MATLAB in batch mode across multiple steps is expected. For instance, when I combine installing my toolbox and my (basic) test, everything works fine:

```yaml
      - name: Install and test MHKiT-MATLAB
        run: |
          matlab -batch \
            "matlab.addons.toolbox.installToolbox('mhkit.mltbx'), \
             import mhkit.river.performance.*, \
             [x, y] = circular(30)"
```

```
Run matlab -batch \
  matlab -batch \
    "matlab.addons.toolbox.installToolbox('mhkit.mltbx'), \
     import mhkit.river.performance.*, \
     [x, y] = circular(30)"
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.7.12/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.7.12/x64/lib

	Sponsored License -- for use in support of a program or activity sponsored by MathWorks.
	Not for government, commercial or other non-sponsored organizational use.

[Warning: Name is nonexistent or not a directory: /home/runner/MATLAB
Add-Ons/Toolboxes/mhkit/tests/test_results] 
[> In path (line 109)
In addpath (line 84)
In matlab.addons.enableAddon (line 82)
In matlab.addons.install/launchInstallation (line 221)
In matlab.addons.install (line 177)
In matlab.addons.toolbox.installToolbox
In mdcsbatch (line 58)
[Warning: Name is nonexistent or not a directory: /home/runner/MATLAB
Add-Ons/Toolboxes/mhkit/tests/test_results/_rels] 
[> In path (line 109)
In addpath (line 84)
In matlab.addons.enableAddon (line 82)
In matlab.addons.install/launchInstallation (line 221)
In matlab.addons.install (line 177)
In matlab.addons.toolbox.installToolbox
In mdcsbatch (line 58)] 
[Warning: Name is nonexistent or not a directory: /home/runner/MATLAB
Add-Ons/Toolboxes/mhkit/tests/test_results/images] 
[> In path (line 109)
In addpath (line 84)
In matlab.addons.enableAddon (line 82)
In matlab.addons.install/launchInstallation (line 221)
In matlab.addons.install (line 177)
In matlab.addons.toolbox.installToolbox
In mdcsbatch (line 58)] 
[Warning: Name is nonexistent or not a directory: /home/runner/MATLAB
Add-Ons/Toolboxes/mhkit/tests/test_results/stylesheets] 
[> In path (line 109)
In addpath (line 84)
In matlab.addons.enableAddon (line 82)
In matlab.addons.install/launchInstallation (line 221)
In matlab.addons.install (line 177)
In matlab.addons.toolbox.installToolbox
In mdcsbatch (line 58)] 

ans = 

  struct with fields:

       Name: 'mhkit'
    Version: '0.3.2'
       Guid: 'a2dc6eda-931e-408a-8e3c-8f63d1f9da82'


x =

    30


y =

   1.1310e+04
```

However, when I split the installation and the test step it fails:

```yaml
      - name: Install MHKiT-MATLAB
        run: |
          matlab -batch \
            "matlab.addons.toolbox.installToolbox('mhkit.mltbx')"
      - name: Run basic test
        run: |
          matlab -batch \
            "import mhkit.river.performance.*, \
             [x, y] = circular(30)"
```

```
Run matlab -batch \

	Sponsored License -- for use in support of a program or activity sponsored by MathWorks.
	Not for government, commercial or other non-sponsored organizational use.

[Warning: Name is nonexistent or not a directory: /home/runner/MATLAB
Add-Ons/Toolboxes/mhkit/tests/test_results] 
[> In path (line 109)
In addpath (line 84)
In matlab.addons.enableAddon (line 82)
In matlab.addons.install/launchInstallation (line 221)
In matlab.addons.install (line 177)
In matlab.addons.toolbox.installToolbox
In mdcsbatch (line 58)] 
[Warning: Name is nonexistent or not a directory: /home/runner/MATLAB
Add-Ons/Toolboxes/mhkit/tests/test_results/_rels] 
[> In path (line 109)
In addpath (line 84)
In matlab.addons.enableAddon (line 82)
In matlab.addons.install/launchInstallation (line 221)
In matlab.addons.install (line 177)
In matlab.addons.toolbox.installToolbox
In mdcsbatch (line 58)] 
[Warning: Name is nonexistent or not a directory: /home/runner/MATLAB
Add-Ons/Toolboxes/mhkit/tests/test_results/images] 
[> In path (line 109)
In addpath (line 84)
In matlab.addons.enableAddon (line 82)
In matlab.addons.install/launchInstallation (line 221)
In matlab.addons.install (line 177)
In matlab.addons.toolbox.installToolbox
In mdcsbatch (line 58)] 
[Warning: Name is nonexistent or not a directory: /home/runner/MATLAB
Add-Ons/Toolboxes/mhkit/tests/test_results/stylesheets] 
[> In path (line 109)
In addpath (line 84)
In matlab.addons.enableAddon (line 82)
In matlab.addons.install/launchInstallation (line 221)
In matlab.addons.install (line 177)
In matlab.addons.toolbox.installToolbox
In mdcsbatch (line 58)] 

ans = 

  struct with fields:

       Name: 'mhkit'
    Version: '0.3.2'
       Guid: 'a2dc6eda-931e-408a-8e3c-8f63d1f9da82'
```

```
Run matlab -batch \
  matlab -batch \
    "import mhkit.river.performance.*, \
     [x, y] = circular(30)"
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.7.12/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.7.12/x64/lib

	Sponsored License -- for use in support of a program or activity sponsored by MathWorks.
	Not for government, commercial or other non-sponsored organizational use.

{Undefined function 'circular' for input arguments of type 'double'.
} 
Error: Process completed with exit code 1.
```

Is this expected behaviour? The full (working) workflow is as follows:

```yaml
name: Run MATLAB tests

on:
  push:
    branches: [ github_actions ]
  pull_request:
    branches: [ github_actions ]

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]
    env:
      mhkit-python-dir: 'MHKiT-Python'
    steps:
      - name: Check out MHKiT-MATLAB
        uses: actions/checkout@v2
      - name: Check out MHKiT-Python
        uses: actions/checkout@v2
        with:
          repository: 'MHKiT-Software/MHKiT-Python'
          path: ${{env.mhkit-python-dir}}
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install MHKiT-Python
        run: python -m pip install -e . "matplotlib<3.4.2"
        working-directory: ${{env.mhkit-python-dir}}
      - name: Install and test MHKiT-MATLAB
        run: |
          matlab -batch \
            "matlab.addons.toolbox.installToolbox('mhkit.mltbx'), \
             import mhkit.river.performance.*, \
             [x, y] = circular(30)"
```
